### ISSUE TITLE
Який сенс це робити? Кожна маленька модифікація, і змінюється весь рядок, так на багато важче не тільки відслідкувати зміни і робити ревью, але й впринципі робити якісь зміни і пропозиції.

### ISSUE THREAD

**Issue by gusarov112** [lollypot/k8s-runners#3]
https://github.com/lollypot/k8s-runners/blob/a0d803a354cf080ff55f62697e3da92d8583b195/dockerfiles/hammer.py#L5

**Comment by lollypot** [comment]
Щоб гітхаб не просканував та не заблокував цей проєкт/аккаунт. Але ви праві - так не зручно, перезалив.
